site_name: RDV
site_description: Render, Diff, and Validate GitOps changes
site_url: https://dlactin.github.io/rdv/

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.instant
    - search.suggest
    - search.highlight
    - content.code.copy

extra:
  version:
    method: mike

repo_url: https://github.com/dlactin/rdv
repo_name: dlactin/rdv

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables

plugins:
  - search
